spring:
  profiles:
    active: dev
  servlet:
    multipart: # configuring file uploads
      max-file-size: 50MB # This sets the max file size to be uploaded
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/